config/routes.rb
Rails.application.routes.draw do

	resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
	get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/home'

  root 'static_pages#landing_page'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @products = Product.where("name ilike ?", "%#{search_term}%" )
      else
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      end

    else
      @products = Product.all
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def landing_page
      @products = Product.limit(3)
  end
  def home
    redirect_to(static_pages_index_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Products", products_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to "Orders", orders_path %></li>
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <%= form_tag("/products", method: "get", class: "navbar-form navbar-left", role: "search") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>



<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Index view.</h1>

app/views/orders/show.html.erb
<h1>Show view</h1>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row col-md-12">
      <div class="form-horizontal">
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </div>
        <div class="field">
          <%= f.label :image_url %><br>
          <%= f.text_field :image_url %>
        </div>
        <div class="field">
          <%= f.label :colour %><br>
          <%= f.text_field :colour %>
        </div>
        <div class="field">
          <%= f.label :price %><br>
          <%= f.text_field :price %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
  </div>

<% end %>

app/views/products/_product.html.erb
<tr class="row">
<td class="product-table data col-md-2"><%= product.name %></td>
<td class="product-table data col-md-6"><%= product.description %></td>
<td class="product-table data col-md-1"><%= product.image_url %></td>
<td class="product-table data col-md-1"><%= product.colour %></td>
<td class="product-table data col-md-1">$<%= product.price %></td>
<div class="col-md-1">
  <td class="links"><%= link_to 'Show', product %></td>
  <td class="links"><%= link_to 'Edit', edit_product_path(product) %></td>
  <td class="links"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</div>
</tr>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
<div class="container">
    <table class="product-table table table-striped">
      <thead>
        <tr class="row">
          <th>Name</th>
          <th>Description</th>
          <th>Image url</th>
          <th>Color</th>
          <th>Price</th>
          <th class="links" colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>
</div>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>
<p>
  <strong>Color:</strong>
  <%= @product.colour %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Welcome the date and time is <%= Time.now =%> </p>
<%= image_tag("images.jpeg") %>

app/views/static_pages/landing_page.html.erb
<div id="carousel-products" class="carousel slide" data-ride="carousel">
  <!-- indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-products" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-products" data-slide-to="1"></li>
    <li data-target="#carousel-products" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides-->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url, alt: product.name) %>
      <div class="carousel-caption">
        <%= product.name %> <br>
        <div class="landing-page-link">
        <%= link_to("Product Details", product) %>
        </div>
      </div>
    </div>
      <% end %>
    </div>
  <!-- Carousel controls-->
  <a class="left carousel-control" href="#carousel-products" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true">
      <span class="sr-only">Previous</span>
    </span>
  </a>
  <a class="right carousel-control" href="#carousel-products" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true">
      <span class="sr-only">Next</span>
    </span>
  </a>
</div>
<%= params[:example_key].to_s %>